# this same shows how we can extend/change an existing official image from Docker Hub

FROM nginx:latest
# highly recommend you always pin versions for anything beyond dev/learn

#Change default working directory for html files 
WORKDIR /usr/share/nginx/html
# change working directory to root of nginx webhost
# using WORKDIR is prefered to using 'RUN cd /some/path'

#Copy index file from this to default nginx folder

COPY index.html index.html

# I don't have to specify EXPOSE or CMD because they're in my FROM
